name: Community Release

"on":
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - v*-rc*

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Setup qemu
        id: qemu
        uses: docker/setup-qemu-action@v3

      - name: Setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Hub login
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Server meta
        id: server
        uses: docker/metadata-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            s4m3l0/semaphore
          labels: |
            org.opencontainers.image.vendor=s4m3l0
          tags: |
            type=raw,value=${{ github.ref_name }}
          flavor: |
            latest=true

      - name: Server build
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: deployment/docker/server/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.server.outputs.labels }}
          tags: ${{ steps.server.outputs.tags }}

      - name: Server build with Ansible 2.16.5
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          build-args: |
            ANSIBLE_VERSION=9.4.0
          file: deployment/docker/server/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.server.outputs.labels }}
          tags: s4m3l0/semaphore:${{ github.ref_name }}-ansible2.16.5

      # - name: Server build with PowerShell 7.5.0
      #   uses: docker/build-push-action@v6
      #   with:
      #     builder: ${{ steps.buildx.outputs.name }}
      #     context: .
      #     build-args: |
      #       POWERSHELL_VERSION=7.5.0
      #       SEMAPHORE_IMAGE=s4m3l0/semaphore
      #       SEMAPHORE_VERSION=${{ github.ref_name }}
      #     file: deployment/docker/server/powershell/Dockerfile
      #     platforms: linux/amd64
      #     push: ${{ github.event_name != 'pull_request' }}
      #     labels: ${{ steps.server.outputs.labels }}
      #     tags: s4m3l0/semaphore:${{ github.ref_name }}-powershell7.5.0

      - name: Runner meta
        id: runner
        uses: docker/metadata-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            s4m3l0/runner
          labels: |
            org.opencontainers.image.vendor=s4m3l0
          tags: |
            type=raw,value=${{ github.ref_name }}
          flavor: |
            latest=true

      - name: Runner build
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: deployment/docker/runner/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.runner.outputs.labels }}
          tags: ${{ steps.runner.outputs.tags }}

      - name: Runner build with Ansible 2.16.5
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          build-args: |
            ANSIBLE_VERSION=9.4.0
          file: deployment/docker/runner/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.runner.outputs.labels }}
          tags: s4m3l0/runner:${{ github.ref_name }}-ansible2.16.5

    # - name: Runner build with PowerShell 7.5.0
    #   uses: docker/build-push-action@v6
    #   with:
    #     builder: ${{ steps.buildx.outputs.name }}
    #     context: .
    #     build-args: |
    #       POWERSHELL_VERSION=7.5.0
    #       SEMAPHORE_IMAGE=s4m3l0/runner
    #       SEMAPHORE_VERSION=${{ github.ref_name }}
    #     file: deployment/docker/server/powershell/Dockerfile
    #     platforms: linux/amd64
    #     push: ${{ github.event_name != 'pull_request' }}
    #     labels: ${{ steps.runner.outputs.labels }}
    #     tags: s4m3l0/runner:${{ github.ref_name }}-powershell7.5.0
